version: 2.1

jobs:
  cypress-tests:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Prepare results folders
          command: |
            mkdir -p test-results
            mkdir -p cypress-report

      - run:
          name: Run Cypress tests (JUnit + Mochawesome)
          command: |
            npx cypress run \
            --reporter mocha-multi-reporters \
            --reporter-options "configFile=mocha-reporters.json"
          no_output_timeout: 10m
          when: always

      - run:
           name: Generate Mochawesome HTML
           command: |
                  npx mochawesome-merge "cypress-report/*.json" -o cypress-report/merged.json
                  npx marge cypress-report/merged.json -f index -o cypress-report
           when: always   

      - run:
         name: Debug report files
        command: |
          echo "=== cypress-report ==="
          ls -la cypress-report || true
        when: always      

      - persist_to_workspace:
          root: .
          paths:
            - cypress-report
            - test-results

      - store_test_results:
          path: test-results

  report:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: .

      - store_artifacts:
          path: cypress-report
          destination: cypress-report

      - run:
          name: Display report URL
          command: |
            echo "📊 Test Report is available at:"
            echo "https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/cypress-report/index.html"
          when: always

workflows:
  cypress-workflow:
    jobs:
      - cypress-tests
      - report:
          requires:
            - cypress-tests