jobs:
  cypress-tests:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  cypress-workflow:
    jobs:
      - cypress-tests
