version: 2.1

jobs:
  cypress-tests:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress tests
          command: npx cypress run
      - persist_to_workspace:
          root: .
          paths:
            - cypress-report
            - test-results

  report:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: cypress-report
          destination: cypress-report

workflows:
  cypress-workflow:
    jobs:
      - cypress-tests
      - report:
          requires:
            - cypress-tests